-- Create user activity progress table to track activity status
CREATE TABLE "public"."user_activity_progress" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile_id" bigint not null,
    "activity_id" bigint not null,
    "status" text not null default 'not_started' check (status in ('not_started', 'started', 'completed')),
    "started_at" timestamp with time zone,
    "completed_at" timestamp with time zone,
    "photo_url" text,
    "notes" text
);

-- Add primary key
ALTER TABLE "public"."user_activity_progress" ADD CONSTRAINT "user_activity_progress_pkey" PRIMARY KEY ("id");

-- Add unique constraint to prevent duplicate entries for same user and activity
ALTER TABLE "public"."user_activity_progress" ADD CONSTRAINT "user_activity_progress_user_activity_unique" UNIQUE ("profile_id", "activity_id");

-- Add foreign key constraints
ALTER TABLE "public"."user_activity_progress" ADD CONSTRAINT "user_activity_progress_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles" ("id") ON DELETE CASCADE;
ALTER TABLE "public"."user_activity_progress" ADD CONSTRAINT "user_activity_progress_activity_id_fkey" FOREIGN KEY ("activity_id") REFERENCES "public"."activities" ("id") ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE "public"."user_activity_progress" ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Users can view their own activity progress" ON "public"."user_activity_progress"
    FOR SELECT USING (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can insert their own activity progress" ON "public"."user_activity_progress"
    FOR INSERT WITH CHECK (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can update their own activity progress" ON "public"."user_activity_progress"
    FOR UPDATE USING (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

-- Grant permissions
GRANT ALL ON TABLE "public"."user_activity_progress" TO "authenticated";
GRANT ALL ON TABLE "public"."user_activity_progress" TO "service_role";

-- Create indexes for better performance
CREATE INDEX "user_activity_progress_profile_id_idx" ON "public"."user_activity_progress" ("profile_id");
CREATE INDEX "user_activity_progress_activity_id_idx" ON "public"."user_activity_progress" ("activity_id");
CREATE INDEX "user_activity_progress_status_idx" ON "public"."user_activity_progress" ("status");
