-- Create pack_activities junction table
CREATE TABLE "public"."pack_activities" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "pack_id" bigint not null,
    "activity_id" bigint not null,
    "order" integer not null default 0
);

-- Add primary key
ALTER TABLE "public"."pack_activities" add constraint "pack_activities_pkey" PRIMARY KEY (id);

-- Add foreign key constraints
ALTER TABLE "public"."pack_activities" 
ADD CONSTRAINT "pack_activities_pack_id_fkey" 
FOREIGN KEY (pack_id) REFERENCES packs(id) ON DELETE CASCADE;

ALTER TABLE "public"."pack_activities" 
ADD CONSTRAINT "pack_activities_activity_id_fkey" 
FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE "public"."pack_activities" enable row level security;

-- Grant permissions
GRANT ALL ON "public"."pack_activities" TO "anon";
GRANT ALL ON "public"."pack_activities" TO "authenticated";
GRANT ALL ON "public"."pack_activities" TO "service_role";

-- Create policy for read access
CREATE POLICY "Enable read access for all users"
ON "public"."pack_activities"
AS PERMISSIVE
FOR SELECT
TO public
USING (true);
