-- Create badges system
-- This allows users to earn badges for various achievements

-- Create badges table
CREATE TABLE "public"."badges" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text not null,
    "image_url" text not null,
    "category" text not null check (category in ('xp', 'pack', 'team', 'special')),
    "requirement_value" integer not null,
    "requirement_type" text not null check (requirement_type in ('xp_gained', 'packs_completed', 'activities_completed', 'team_xp')),
    constraint badges_pkey primary key (id)
);

-- Create user_badges table to track earned badges
CREATE TABLE "public"."user_badges" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null references auth.users(id) on delete cascade,
    "badge_id" bigint not null references badges(id) on delete cascade,
    "earned_at" timestamp with time zone not null default now(),
    constraint user_badges_pkey primary key (id),
    constraint user_badges_unique unique (user_id, badge_id)
);

-- Enable RLS
ALTER TABLE "public"."badges" enable row level security;
ALTER TABLE "public"."user_badges" enable row level security;

-- Create indexes
CREATE INDEX badges_category_idx ON badges(category);
CREATE INDEX user_badges_user_id_idx ON user_badges(user_id);
CREATE INDEX user_badges_badge_id_idx ON user_badges(badge_id);

-- Insert initial badge data
INSERT INTO "public"."badges" (name, description, image_url, category, requirement_value, requirement_type) VALUES
('First Steps', 'Complete your first activity and earn your first XP!', '🏃‍♂️', 'xp', 1, 'xp_gained'),
('Explorer', 'Earn 50 XP through completing activities', '🗺️', 'xp', 50, 'xp_gained'),
('Adventure Master', 'Earn 100 XP through completing activities', '🏆', 'xp', 100, 'xp_gained'),
('Pack Pioneer', 'Complete your first pack of activities', '📦', 'pack', 1, 'packs_completed'),
('Team Player', 'Contribute 25 XP to your team', '👥', 'team', 25, 'team_xp'),
('Nature Enthusiast', 'Complete 10 nature-related activities', '🌿', 'special', 10, 'activities_completed');

-- RLS Policies for badges table
CREATE POLICY "Anyone can view badges" ON "public"."badges"
    FOR SELECT USING (true);

-- RLS Policies for user_badges table
CREATE POLICY "Users can view their own badges" ON "public"."user_badges"
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own badges" ON "public"."user_badges"
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Grant permissions
GRANT SELECT ON "public"."badges" TO authenticated;
GRANT SELECT, INSERT ON "public"."user_badges" TO authenticated;
