-- Step 10.3: Persisted Explore point catalogue (Stoke-first).
-- Supersedes runtime OSM tile acquisition / Edge stop generation for nearby.

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA extensions;

-- ---------------------------------------------------------------------------
-- Catalogue versions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.explore_point_catalogue_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_id text NOT NULL,
  generation_version integer NOT NULL,
  source_revision text NOT NULL,
  status text NOT NULL DEFAULT 'building'
    CHECK (status IN ('building', 'validating', 'ready', 'active', 'retired', 'failed')),
  point_count integer NOT NULL DEFAULT 0 CHECK (point_count >= 0),
  coverage_km2 double precision,
  created_at timestamptz NOT NULL DEFAULT now(),
  activated_at timestamptz,
  retired_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT explore_catalogue_generation_positive CHECK (generation_version > 0),
  CONSTRAINT explore_catalogue_region_gen_rev_uidx UNIQUE (region_id, generation_version, source_revision)
);

CREATE INDEX IF NOT EXISTS explore_catalogue_versions_status_idx
  ON public.explore_point_catalogue_versions (status);

COMMENT ON TABLE public.explore_point_catalogue_versions IS
  'Versioned Explore point catalogues. Nearby queries use status=active only.';

ALTER TABLE public.explore_point_catalogue_versions ENABLE ROW LEVEL SECURITY;
-- No policies for authenticated — service_role / SECURITY DEFINER RPCs only.
GRANT ALL ON public.explore_point_catalogue_versions TO service_role;
GRANT SELECT ON public.explore_point_catalogue_versions TO authenticated;

-- ---------------------------------------------------------------------------
-- Points
-- ---------------------------------------------------------------------------
-- point_type integers (stable; never silently reassign):
-- 1 footpath, 2 path, 3 sidewalk, 4 cycleway_walk, 5 plaza,
-- 6 park, 7 garden, 8 recreation_ground, 9 common, 10 venue, 11 pedestrian (reserved)

CREATE TABLE IF NOT EXISTS public.explore_points (
  id text NOT NULL,
  catalogue_version_id bigint NOT NULL
    REFERENCES public.explore_point_catalogue_versions (id) ON DELETE CASCADE,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  point_type smallint NOT NULL,
  generation_version integer NOT NULL,
  source_revision text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  source_type text NOT NULL,
  source_feature_id text,
  confidence real,
  environment_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  location extensions.geography(Point, 4326)
    GENERATED ALWAYS AS (
      extensions.ST_SetSRID(extensions.ST_MakePoint(longitude, latitude), 4326)::extensions.geography
    ) STORED,
  PRIMARY KEY (catalogue_version_id, id),
  CONSTRAINT explore_points_lat_range CHECK (latitude >= -90 AND latitude <= 90),
  CONSTRAINT explore_points_lon_range CHECK (longitude >= -180 AND longitude <= 180),
  CONSTRAINT explore_points_type_known CHECK (point_type BETWEEN 1 AND 11),
  CONSTRAINT explore_points_generation_positive CHECK (generation_version > 0)
);

CREATE INDEX IF NOT EXISTS explore_points_location_gix
  ON public.explore_points USING GIST (location);

CREATE INDEX IF NOT EXISTS explore_points_active_catalogue_idx
  ON public.explore_points (catalogue_version_id)
  WHERE active = true;

CREATE INDEX IF NOT EXISTS explore_points_id_idx
  ON public.explore_points (id);

COMMENT ON TABLE public.explore_points IS
  'Persisted Explore claimable points. Compact catalogue; OSM features are not stored here.';

ALTER TABLE public.explore_points ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.explore_points TO service_role;
GRANT SELECT ON public.explore_points TO authenticated;

-- ---------------------------------------------------------------------------
-- Nearby RPC (authenticated; uses spatial index)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_explore_points_nearby(
  p_latitude double precision,
  p_longitude double precision,
  p_radius_metres double precision DEFAULT 1000,
  p_limit_count integer DEFAULT 40
)
RETURNS TABLE (
  id text,
  latitude double precision,
  longitude double precision,
  point_type smallint,
  source_type text,
  generation_version integer,
  source_revision text,
  distance_metres double precision,
  environment_profile jsonb,
  source_feature_id text,
  confidence real
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_radius double precision;
  v_limit integer;
  v_origin extensions.geography;
BEGIN
  IF p_latitude IS NULL OR p_longitude IS NULL
     OR p_latitude < -90 OR p_latitude > 90
     OR p_longitude < -180 OR p_longitude > 180 THEN
    RAISE EXCEPTION 'invalid_coordinates' USING ERRCODE = '22023';
  END IF;

  v_radius := coalesce(p_radius_metres, 1000);
  IF v_radius <= 0 OR v_radius > 2000 THEN
    RAISE EXCEPTION 'radius_too_large' USING ERRCODE = '22023';
  END IF;

  v_limit := least(greatest(coalesce(p_limit_count, 40), 1), 100);
  v_origin := extensions.ST_SetSRID(extensions.ST_MakePoint(p_longitude, p_latitude), 4326)::extensions.geography;

  RETURN QUERY
  SELECT
    ep.id,
    ep.latitude,
    ep.longitude,
    ep.point_type,
    ep.source_type,
    ep.generation_version,
    ep.source_revision,
    extensions.ST_Distance(ep.location, v_origin)::double precision AS distance_metres,
    ep.environment_profile,
    ep.source_feature_id,
    ep.confidence
  FROM public.explore_points ep
  INNER JOIN public.explore_point_catalogue_versions cv
    ON cv.id = ep.catalogue_version_id
  WHERE cv.status = 'active'
    AND ep.active = true
    AND extensions.ST_DWithin(ep.location, v_origin, v_radius)
  ORDER BY distance_metres ASC
  LIMIT v_limit;
END;
$$;

REVOKE ALL ON FUNCTION public.get_explore_points_nearby(double precision, double precision, double precision, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_explore_points_nearby(double precision, double precision, double precision, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_explore_points_nearby(double precision, double precision, double precision, integer) TO service_role;

-- ---------------------------------------------------------------------------
-- Load one active point by id (verify/claim)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_explore_point_by_id(
  p_stop_id text
)
RETURNS TABLE (
  id text,
  latitude double precision,
  longitude double precision,
  point_type smallint,
  source_type text,
  generation_version integer,
  source_revision text,
  environment_profile jsonb,
  source_feature_id text,
  confidence real,
  active boolean,
  catalogue_status text
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
  IF p_stop_id IS NULL OR length(trim(p_stop_id)) = 0 THEN
    RAISE EXCEPTION 'invalid_stop_id' USING ERRCODE = '22023';
  END IF;

  RETURN QUERY
  SELECT
    ep.id,
    ep.latitude,
    ep.longitude,
    ep.point_type,
    ep.source_type,
    ep.generation_version,
    ep.source_revision,
    ep.environment_profile,
    ep.source_feature_id,
    ep.confidence,
    ep.active,
    cv.status AS catalogue_status
  FROM public.explore_points ep
  INNER JOIN public.explore_point_catalogue_versions cv
    ON cv.id = ep.catalogue_version_id
  WHERE ep.id = trim(p_stop_id)
    AND cv.status IN ('active', 'retired')
  ORDER BY
    CASE WHEN cv.status = 'active' THEN 0 ELSE 1 END,
    cv.activated_at DESC NULLS LAST
  LIMIT 1;
END;
$$;

REVOKE ALL ON FUNCTION public.get_explore_point_by_id(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_explore_point_by_id(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_explore_point_by_id(text) TO service_role;

-- ---------------------------------------------------------------------------
-- Activate catalogue version (service_role)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.activate_explore_catalogue_version(
  p_catalogue_version_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_region text;
  v_count integer;
BEGIN
  SELECT region_id, point_count INTO v_region, v_count
  FROM public.explore_point_catalogue_versions
  WHERE id = p_catalogue_version_id
    AND status IN ('ready', 'active');

  IF v_region IS NULL THEN
    RAISE EXCEPTION 'catalogue_not_ready' USING ERRCODE = 'P0001';
  END IF;

  UPDATE public.explore_point_catalogue_versions
  SET status = 'retired',
      retired_at = now()
  WHERE region_id = v_region
    AND status = 'active'
    AND id <> p_catalogue_version_id;

  UPDATE public.explore_point_catalogue_versions
  SET status = 'active',
      activated_at = now(),
      retired_at = null
  WHERE id = p_catalogue_version_id;

  RETURN jsonb_build_object(
    'ok', true,
    'catalogue_version_id', p_catalogue_version_id,
    'region_id', v_region,
    'point_count', v_count
  );
END;
$$;

REVOKE ALL ON FUNCTION public.activate_explore_catalogue_version(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.activate_explore_catalogue_version(bigint) TO service_role;

-- Coverage probe (any active point within large radius?)
CREATE OR REPLACE FUNCTION public.explore_has_active_coverage(
  p_latitude double precision,
  p_longitude double precision,
  p_probe_metres double precision DEFAULT 5000
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, extensions
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.explore_points ep
    INNER JOIN public.explore_point_catalogue_versions cv ON cv.id = ep.catalogue_version_id
    WHERE cv.status = 'active'
      AND ep.active = true
      AND extensions.ST_DWithin(
        ep.location,
        extensions.ST_SetSRID(extensions.ST_MakePoint(p_longitude, p_latitude), 4326)::extensions.geography,
        least(greatest(coalesce(p_probe_metres, 5000), 100), 50000)
      )
  );
$$;

REVOKE ALL ON FUNCTION public.explore_has_active_coverage(double precision, double precision, double precision) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.explore_has_active_coverage(double precision, double precision, double precision) TO authenticated;
GRANT EXECUTE ON FUNCTION public.explore_has_active_coverage(double precision, double precision, double precision) TO service_role;
