-- World Exploration: seeded map locations, rarity-tiered trading cards ("collectibles"), and
-- per-profile inventory/visit history. Squashed replacement of the five original 20260718*
-- explore migrations -- this feature has never shipped past `feature/explore`, so the schema is
-- reshaped in place rather than layered with ALTERs. Anyone with a local Supabase dev instance
-- must run `supabase db reset` after pulling this change.
--
-- Deliberately not using the `huntly_` prefix / uuid-PK style from
-- 20260625110000_huntly_core_tables.sql -- those tables belong to a separate scavenger-hunt
-- feature being ported from a different app. These tables follow the app's actual dominant
-- convention (bigint identity PKs, profile_id FK with cascade, RLS via profiles.user_id).

CREATE TYPE "public"."explore_collectible_rarity" AS ENUM (
  'common',
  'uncommon',
  'rare',
  'epic',
  'legendary'
);

-- Admin-seeded points of interest on the world map.
CREATE TABLE "public"."explore_locations" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "name" text not null,
  "description" text,
  "image_url" text,
  "latitude" double precision not null,
  "longitude" double precision not null,
  "radius_meters" integer not null default 50 check (radius_meters between 10 and 500),
  "is_active" boolean not null default true,
  "created_by" uuid references auth.users(id),
  constraint explore_locations_pkey primary key (id)
);

CREATE INDEX explore_locations_active_idx ON explore_locations (is_active);
CREATE INDEX explore_locations_lat_lng_idx ON explore_locations (latitude, longitude);

ALTER TABLE "public"."explore_locations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone authenticated can view active locations" ON "public"."explore_locations"
  FOR SELECT TO authenticated USING (is_active = true);

GRANT SELECT ON TABLE "public"."explore_locations" TO "authenticated";
GRANT ALL ON TABLE "public"."explore_locations" TO "service_role";

-- Admin-editable card categories (Animals, Habitats, Food, ...). A lookup table rather than an
-- enum since the category set is expected to grow as content is authored, unlike rarity.
CREATE TABLE "public"."explore_collectible_categories" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "key" text not null,
  "label" text not null,
  "icon" text,
  "color" text,
  "sort_order" integer not null default 0,
  "is_active" boolean not null default true,
  constraint explore_collectible_categories_pkey primary key (id),
  constraint explore_collectible_categories_key_unique unique (key)
);

CREATE INDEX explore_collectible_categories_active_idx ON explore_collectible_categories (is_active);

ALTER TABLE "public"."explore_collectible_categories" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone authenticated can view active categories" ON "public"."explore_collectible_categories"
  FOR SELECT TO authenticated USING (is_active = true);

GRANT SELECT ON TABLE "public"."explore_collectible_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."explore_collectible_categories" TO "service_role";

-- Catalog of collectible trading cards, tiered by rarity and grouped by category. `weight` drives
-- the global weighted draw at check-in time (see check_in_to_explore_location) -- replaces the
-- old per-location `explore_location_collectibles` spawn pool, since v2 draws from the whole
-- active catalog regardless of which location was checked into.
CREATE TABLE "public"."explore_collectibles" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "name" text not null,
  "description" text,
  "image_url" text not null,
  "rarity" explore_collectible_rarity not null default 'common',
  "category_id" bigint references explore_collectible_categories(id) on delete set null,
  "weight" integer not null default 100 check (weight > 0),
  "flavor_text" text,
  "is_active" boolean not null default true,
  constraint explore_collectibles_pkey primary key (id)
);

CREATE INDEX explore_collectibles_rarity_idx ON explore_collectibles (rarity);
CREATE INDEX explore_collectibles_category_idx ON explore_collectibles (category_id);
CREATE INDEX explore_collectibles_active_idx ON explore_collectibles (is_active);

ALTER TABLE "public"."explore_collectibles" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone authenticated can view active collectibles" ON "public"."explore_collectibles"
  FOR SELECT TO authenticated USING (is_active = true);

GRANT SELECT ON TABLE "public"."explore_collectibles" TO "authenticated";
GRANT ALL ON TABLE "public"."explore_collectibles" TO "service_role";

-- Per-profile inventory. Duplicates increment `count` rather than creating extra rows --
-- revisits are expected and should feel rewarding, not spammy. `first_shiny_discovered_at` marks
-- the first time this profile pulled a shiny (foil) roll of this card -- shiny is a per-pull
-- cosmetic roll independent of which card was drawn (see the RPC), not a distinct catalog row, so
-- it's tracked here rather than as a flag on explore_collectibles.
CREATE TABLE "public"."explore_profile_collectibles" (
  "id" bigint generated by default as identity not null,
  "profile_id" bigint not null references profiles(id) on delete cascade,
  "collectible_id" bigint not null references explore_collectibles(id) on delete cascade,
  "count" integer not null default 1 check (count > 0),
  "first_discovered_at" timestamp with time zone not null default now(),
  "first_discovered_location_id" bigint references explore_locations(id) on delete set null,
  "first_shiny_discovered_at" timestamp with time zone,
  "updated_at" timestamp with time zone not null default now(),
  constraint explore_profile_collectibles_pkey primary key (id),
  constraint explore_profile_collectibles_unique unique (profile_id, collectible_id)
);

CREATE INDEX explore_profile_collectibles_profile_idx ON explore_profile_collectibles (profile_id);

ALTER TABLE "public"."explore_profile_collectibles" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own collectible inventory" ON "public"."explore_profile_collectibles"
  FOR SELECT USING (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

GRANT SELECT ON TABLE "public"."explore_profile_collectibles" TO "authenticated";
GRANT ALL ON TABLE "public"."explore_profile_collectibles" TO "service_role";

-- Discrete check-in log: anti-cheat audit trail. Never a continuous route -- one row per
-- successful check-in, foreground-only, matching the app's location-privacy stance.
CREATE TABLE "public"."explore_visits" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "profile_id" bigint not null references profiles(id) on delete cascade,
  "location_id" bigint not null references explore_locations(id) on delete cascade,
  "collectible_id" bigint not null references explore_collectibles(id) on delete cascade,
  "is_new_collectible" boolean not null,
  "is_shiny" boolean not null default false,
  "submitted_latitude" double precision not null,
  "submitted_longitude" double precision not null,
  "submitted_accuracy_meters" double precision,
  "distance_meters" double precision not null,
  "xp_awarded" integer not null default 0,
  constraint explore_visits_pkey primary key (id)
);

CREATE INDEX explore_visits_profile_created_idx ON explore_visits (profile_id, created_at desc);
CREATE INDEX explore_visits_profile_location_idx ON explore_visits (profile_id, location_id);

ALTER TABLE "public"."explore_visits" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own visit history" ON "public"."explore_visits"
  FOR SELECT USING (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

GRANT SELECT ON TABLE "public"."explore_visits" TO "authenticated";
GRANT ALL ON TABLE "public"."explore_visits" TO "service_role";
