-- Simulated ("fake") explorer activity
--
-- Lets an admin maintain a pool of fake explorer accounts and drip
-- simulated mission completions (feed activity, photos, team points)
-- into the same tables real users write to. Everything is tagged via
-- simulated_accounts so it can be identified, ramped up/down, or purged
-- without touching real user data.

-- Marks which auth.users rows belong to the fake pool. Single source of
-- truth for "is this account simulated" everywhere (admin UI, purge, tick).
create table "public"."simulated_accounts" (
  "user_id" uuid not null,
  "created_at" timestamptz not null default now()
);

alter table "public"."simulated_accounts" add constraint "simulated_accounts_pkey" primary key ("user_id");
alter table "public"."simulated_accounts" add constraint "simulated_accounts_user_id_fkey"
  foreign key ("user_id") references auth.users("id") on delete cascade;

alter table "public"."simulated_accounts" enable row level security;

-- Singleton settings row controlling the drip rate.
create table "public"."simulated_activity_settings" (
  "id" smallint not null default 1,
  "enabled" boolean not null default false,
  "completions_per_day" integer not null default 20,
  "updated_at" timestamptz not null default now()
);

alter table "public"."simulated_activity_settings" add constraint "simulated_activity_settings_pkey" primary key ("id");
alter table "public"."simulated_activity_settings" add constraint "simulated_activity_settings_id_check" check ("id" = 1);

alter table "public"."simulated_activity_settings" enable row level security;

insert into "public"."simulated_activity_settings" ("id", "enabled", "completions_per_day")
values (1, false, 20);

-- Admin-curated photo pool per activity, used to attach a photo to a
-- simulated completion when one is available for that activity.
create table "public"."simulated_activity_photos" (
  "id" bigint generated by default as identity not null,
  "activity_id" bigint not null,
  "photo_url" text not null,
  "created_at" timestamptz not null default now()
);

alter table "public"."simulated_activity_photos" add constraint "simulated_activity_photos_pkey" primary key ("id");
alter table "public"."simulated_activity_photos" add constraint "simulated_activity_photos_activity_id_fkey"
  foreign key ("activity_id") references "public"."activities"("id") on delete cascade;

create index "simulated_activity_photos_activity_id_idx" on "public"."simulated_activity_photos" ("activity_id");

alter table "public"."simulated_activity_photos" enable row level security;

-- All three tables are only ever accessed via the admin app's service-role
-- client or the SECURITY DEFINER tick function below, so no RLS policies
-- are defined (default deny for anon/authenticated, service_role bypasses RLS).

grant all on table "public"."simulated_accounts" to "service_role";
grant all on table "public"."simulated_activity_settings" to "service_role";
grant all on table "public"."simulated_activity_photos" to "service_role";

-- Storage bucket for admin-uploaded simulated activity photos (public read).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'simulated-activity-photos',
  'simulated-activity-photos',
  true,
  15728640, -- 15MB, matches apps/admin/lib/upload-actions.ts
  array['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = true,
  file_size_limit = 15728640,
  allowed_mime_types = array['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/gif'];

create policy "Anyone can view simulated activity photos" on storage.objects
  for select using (bucket_id = 'simulated-activity-photos');

-- Tick function: on each cron run, probabilistically fires a small number
-- of simulated completions (rate derived from completions_per_day) drawn
-- from fake profiles that still have an uncompleted activity available.
create or replace function public.simulated_activity_tick()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_settings record;
  v_rate numeric;
  v_fire_count int;
  v_profile_id bigint;
  v_activity_id bigint;
  v_team_id bigint;
  v_xp int;
  v_title text;
  v_completed_at timestamptz;
  v_photo_url text;
  v_progress_id bigint;
begin
  select * into v_settings from simulated_activity_settings where id = 1;
  if v_settings is null or not v_settings.enabled or v_settings.completions_per_day <= 0 then
    return;
  end if;

  v_rate := v_settings.completions_per_day / 1440.0; -- per-minute rate (cron runs every minute)
  v_fire_count := floor(v_rate) + (case when random() < (v_rate - floor(v_rate)) then 1 else 0 end);

  for i in 1..v_fire_count loop
    v_profile_id := null;

    select p.id, ud.team, a.id, a.xp, a.title
      into v_profile_id, v_team_id, v_activity_id, v_xp, v_title
    from profiles p
    join simulated_accounts sa on sa.user_id = p.user_id
    join user_data ud on ud.user_id = p.user_id
    cross join lateral (
      select act.id, act.xp, act.title
      from activities act
      where not exists (
        select 1 from user_activity_progress uap
        where uap.profile_id = p.id and uap.activity_id = act.id
      )
      order by random()
      limit 1
    ) a
    order by random()
    limit 1;

    if v_profile_id is null then
      continue; -- no fake profile has an uncompleted activity left
    end if;

    v_completed_at := now() - (random() * interval '45 minutes');

    insert into user_activity_progress (profile_id, activity_id, completed_at)
    values (v_profile_id, v_activity_id, v_completed_at)
    returning id into v_progress_id;

    select photo_url into v_photo_url
    from simulated_activity_photos
    where activity_id = v_activity_id
    order by random() limit 1;

    if v_photo_url is not null then
      insert into user_activity_photos (user_activity_id, profile_id, activity_id, photo_url, uploaded_at, status)
      values (v_progress_id, v_profile_id, v_activity_id, v_photo_url, v_completed_at, 1); -- 1 = approved
    end if;

    insert into user_achievements (profile_id, team_id, source, source_id, message, xp, created_at)
    values (v_profile_id, v_team_id, 'simulated_activity', v_activity_id,
            format('Completed %s', coalesce(v_title, 'a mission')), coalesce(v_xp, 0), v_completed_at);
  end loop;
end;
$$;

grant execute on function public.simulated_activity_tick() to service_role;

-- Ensure a single cron job exists (idempotent, mirrors campfire_schedule_tick).
do $$
declare
  existing_job_id integer;
begin
  select jobid into existing_job_id
  from cron.job
  where jobname = 'simulated-activity-tick'
  limit 1;

  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;

  perform cron.schedule(
    'simulated-activity-tick',
    '* * * * *',
    $cmd$ select public.simulated_activity_tick(); $cmd$
  );
end;
$$;
