-- Fixes migration ordering for a from-scratch rebuild (fresh local DB, CI,
-- disaster recovery). 20260529120000_campfire_realtime_scheduled_wait.sql
-- references public.campfire_sessions before it exists in filename order —
-- the table isn't created until 20260620000000_create_campfire_sessions.sql.
-- Every real environment (production) already has both migrations applied
-- and is unaffected by this file. This migration creates the table early so
-- a rebuild doesn't fail; 20260620000000 is guarded to no-op once it finds
-- the objects already here.

DO $$ BEGIN
  CREATE TYPE campfire_session_status AS ENUM (
    'draft', 'scheduled', 'live', 'replay', 'archived'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE campfire_component_type AS ENUM (
    'audio', 'subtitle', 'mission_card', 'submission'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "public"."campfire_sessions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "title" text NOT NULL,
  "status" campfire_session_status NOT NULL DEFAULT 'draft',
  "scheduled_at" timestamptz,
  "duration" integer,
  "description" text,
  "thumbnail_url" text,
  "missions" bigint[] NOT NULL DEFAULT '{}'
);

ALTER TABLE "public"."campfire_sessions" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "Authenticated read non-draft campfire_sessions"
    ON "public"."campfire_sessions" FOR SELECT TO authenticated
    USING (status IN ('scheduled', 'live', 'replay'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "Service role full access to campfire_sessions"
    ON "public"."campfire_sessions" FOR ALL TO service_role
    USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
