-- World Exploration: seeded map locations, rarity-tiered collectibles, and per-profile
-- inventory/visit history. See ai-dev plan "World Exploration: Collectible Discovery Activity".
--
-- Deliberately not using the `huntly_` prefix / uuid-PK style from
-- 20260625110000_huntly_core_tables.sql -- those tables belong to a separate scavenger-hunt
-- feature being ported from a different app. These tables follow the app's actual dominant
-- convention (bigint identity PKs, profile_id FK with cascade, RLS via profiles.user_id).

CREATE TYPE "public"."explore_collectible_rarity" AS ENUM (
  'common',
  'uncommon',
  'rare',
  'epic',
  'legendary'
);

-- Admin-seeded points of interest on the world map.
CREATE TABLE "public"."explore_locations" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "name" text not null,
  "description" text,
  "image_url" text,
  "latitude" double precision not null,
  "longitude" double precision not null,
  "radius_meters" integer not null default 50 check (radius_meters between 10 and 500),
  "is_active" boolean not null default true,
  "created_by" uuid references auth.users(id),
  constraint explore_locations_pkey primary key (id)
);

CREATE INDEX explore_locations_active_idx ON explore_locations (is_active);
CREATE INDEX explore_locations_lat_lng_idx ON explore_locations (latitude, longitude);

ALTER TABLE "public"."explore_locations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone authenticated can view active locations" ON "public"."explore_locations"
  FOR SELECT TO authenticated USING (is_active = true);

GRANT SELECT ON TABLE "public"."explore_locations" TO "authenticated";
GRANT ALL ON TABLE "public"."explore_locations" TO "service_role";

-- Catalog of collectibles, tiered by rarity.
CREATE TABLE "public"."explore_collectibles" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "name" text not null,
  "description" text,
  "image_url" text not null,
  "rarity" explore_collectible_rarity not null default 'common',
  "flavor_text" text,
  "is_active" boolean not null default true,
  constraint explore_collectibles_pkey primary key (id)
);

CREATE INDEX explore_collectibles_rarity_idx ON explore_collectibles (rarity);
CREATE INDEX explore_collectibles_active_idx ON explore_collectibles (is_active);

ALTER TABLE "public"."explore_collectibles" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone authenticated can view active collectibles" ON "public"."explore_collectibles"
  FOR SELECT TO authenticated USING (is_active = true);

GRANT SELECT ON TABLE "public"."explore_collectibles" TO "authenticated";
GRANT ALL ON TABLE "public"."explore_collectibles" TO "service_role";

-- Per-location spawn pool + weights. Deliberately NOT readable by the client: revealing
-- weights/pool contents would let kids look up what a location can drop and kill the surprise.
-- The weighted draw happens server-side inside the check-in RPC.
CREATE TABLE "public"."explore_location_collectibles" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "location_id" bigint not null references explore_locations(id) on delete cascade,
  "collectible_id" bigint not null references explore_collectibles(id) on delete cascade,
  "weight" integer not null default 100 check (weight > 0),
  constraint explore_location_collectibles_pkey primary key (id),
  constraint explore_location_collectibles_unique unique (location_id, collectible_id)
);

CREATE INDEX explore_location_collectibles_location_idx ON explore_location_collectibles (location_id);

ALTER TABLE "public"."explore_location_collectibles" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."explore_location_collectibles" TO "service_role";

-- Per-profile inventory. Duplicates increment `count` rather than creating extra rows --
-- revisits are expected and should feel rewarding, not spammy.
CREATE TABLE "public"."explore_profile_collectibles" (
  "id" bigint generated by default as identity not null,
  "profile_id" bigint not null references profiles(id) on delete cascade,
  "collectible_id" bigint not null references explore_collectibles(id) on delete cascade,
  "count" integer not null default 1 check (count > 0),
  "first_discovered_at" timestamp with time zone not null default now(),
  "first_discovered_location_id" bigint references explore_locations(id) on delete set null,
  "updated_at" timestamp with time zone not null default now(),
  constraint explore_profile_collectibles_pkey primary key (id),
  constraint explore_profile_collectibles_unique unique (profile_id, collectible_id)
);

CREATE INDEX explore_profile_collectibles_profile_idx ON explore_profile_collectibles (profile_id);

ALTER TABLE "public"."explore_profile_collectibles" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own collectible inventory" ON "public"."explore_profile_collectibles"
  FOR SELECT USING (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

GRANT SELECT ON TABLE "public"."explore_profile_collectibles" TO "authenticated";
GRANT ALL ON TABLE "public"."explore_profile_collectibles" TO "service_role";

-- Discrete check-in log: anti-cheat audit trail. Never a continuous route -- one row per
-- successful check-in, foreground-only, matching the app's location-privacy stance.
CREATE TABLE "public"."explore_visits" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "profile_id" bigint not null references profiles(id) on delete cascade,
  "location_id" bigint not null references explore_locations(id) on delete cascade,
  "collectible_id" bigint not null references explore_collectibles(id) on delete cascade,
  "is_new_collectible" boolean not null,
  "submitted_latitude" double precision not null,
  "submitted_longitude" double precision not null,
  "submitted_accuracy_meters" double precision,
  "distance_meters" double precision not null,
  "xp_awarded" integer not null default 0,
  constraint explore_visits_pkey primary key (id)
);

CREATE INDEX explore_visits_profile_created_idx ON explore_visits (profile_id, created_at desc);
CREATE INDEX explore_visits_profile_location_idx ON explore_visits (profile_id, location_id);

ALTER TABLE "public"."explore_visits" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own visit history" ON "public"."explore_visits"
  FOR SELECT USING (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

GRANT SELECT ON TABLE "public"."explore_visits" TO "authenticated";
GRANT ALL ON TABLE "public"."explore_visits" TO "service_role";
