-- Create categories table: id (increment), icon (image url), name (category name)
CREATE TABLE "public"."categories" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "icon" text,
  "name" text NOT NULL
);

ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;

-- Allow read for authenticated (mobile app) and full access for service_role
CREATE POLICY "Categories are viewable by authenticated users"
  ON "public"."categories"
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Categories are manageable by service role"
  ON "public"."categories"
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Admins table exists; if admin access is via service_role or custom role, add policy as needed.
-- For admin app using service_role or authenticated with admin check, add:
CREATE POLICY "Categories are viewable by anon"
  ON "public"."categories"
  FOR SELECT
  TO anon
  USING (true);

COMMENT ON TABLE "public"."categories" IS 'Activity categories with icon URL and display name. Referenced by activities.categories (array of category ids).';
