-- User-submitted feedback (mobile + admin). Table may already exist on older prod; keep migration safe to re-run.
CREATE TABLE IF NOT EXISTS "public"."user_feedback" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "profile_id" bigint REFERENCES public.profiles(id) ON DELETE SET NULL,
  "team_id" bigint REFERENCES public.teams(id) ON DELETE SET NULL,
  "user_id" uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  "source" text,
  "screen" text,
  "message" text,
  "device_platform" text,
  "device_model" text,
  "app_version" text,
  "app_build" text,
  "app_environment" text,
  "handled" boolean DEFAULT false,
  "handled_at" timestamptz,
  "handled_by" text,
  "extra" jsonb
);

ALTER TABLE "public"."user_feedback"
  ADD COLUMN IF NOT EXISTS "handled_at" timestamptz;

ALTER TABLE "public"."user_feedback"
  ADD COLUMN IF NOT EXISTS "handled_by" text;

ALTER TABLE "public"."user_feedback" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can insert user_feedback" ON "public"."user_feedback";
CREATE POLICY "Users can insert user_feedback"
  ON "public"."user_feedback" FOR INSERT TO authenticated
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON "public"."user_feedback" TO service_role;

COMMENT ON TABLE "public"."user_feedback" IS 'Free-text feedback from the app; admin list uses service_role.';
