-- Create user_achievements table for recording achievements (e.g. mission completions)
CREATE TABLE "public"."user_achievements" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" bigint NOT NULL REFERENCES "public"."profiles" ("id") ON DELETE CASCADE,
    "team_id" bigint NOT NULL REFERENCES "public"."teams" ("id") ON DELETE CASCADE,
    "source" text NOT NULL,
    "source_id" bigint NOT NULL,
    "message" text NOT NULL,
    "xp" integer NOT NULL DEFAULT 0,
    "created_at" timestamptz NOT NULL DEFAULT now()
);

-- Indexes for common lookups
CREATE INDEX "user_achievements_profile_id_idx" ON "public"."user_achievements" ("profile_id");
CREATE INDEX "user_achievements_team_id_idx" ON "public"."user_achievements" ("team_id");
CREATE INDEX "user_achievements_created_at_idx" ON "public"."user_achievements" ("created_at" DESC);

-- RLS
ALTER TABLE "public"."user_achievements" ENABLE ROW LEVEL SECURITY;

-- Users can view achievements for their own profiles
CREATE POLICY "Users can view own profile achievements" ON "public"."user_achievements"
    FOR SELECT USING (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

-- Users can insert achievements for their own profiles
CREATE POLICY "Users can insert own profile achievements" ON "public"."user_achievements"
    FOR INSERT WITH CHECK (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

-- Grant permissions
GRANT ALL ON TABLE "public"."user_achievements" TO "authenticated";
GRANT ALL ON TABLE "public"."user_achievements" TO "service_role";
