-- Create the journal-photos storage bucket (public, matching user-activity-photos pattern)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'journal-photos',
  'journal-photos',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic']
)
ON CONFLICT (id) DO NOTHING;

-- Storage policies: owner-scoped by user_id prefix in path
CREATE POLICY "Users can upload their own journal photos"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'journal-photos'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users can view their own journal photos"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'journal-photos'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users can delete their own journal photos"
  ON storage.objects FOR DELETE TO authenticated
  USING (
    bucket_id = 'journal-photos'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Main journal entries table
CREATE TABLE IF NOT EXISTS "public"."journal_entries" (
  "id"           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"      uuid   NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  "profile_id"   bigint NOT NULL REFERENCES "public"."profiles" (id) ON DELETE CASCADE,
  "title"        text   NOT NULL,
  "notes"        text,
  "photo_url"    text,
  "activity_tag" text   NOT NULL DEFAULT 'Other',
  "entry_date"   date   NOT NULL DEFAULT CURRENT_DATE,
  "created_at"   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "journal_entries_user_id_idx"
  ON "public"."journal_entries" ("user_id");

CREATE INDEX IF NOT EXISTS "journal_entries_profile_id_idx"
  ON "public"."journal_entries" ("profile_id");

CREATE INDEX IF NOT EXISTS "journal_entries_entry_date_idx"
  ON "public"."journal_entries" ("entry_date" DESC);

CREATE INDEX IF NOT EXISTS "journal_entries_created_at_idx"
  ON "public"."journal_entries" ("created_at" DESC);

ALTER TABLE "public"."journal_entries" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own journal entries"
  ON "public"."journal_entries" FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users can insert own journal entries"
  ON "public"."journal_entries" FOR INSERT
  WITH CHECK (
    user_id = auth.uid()
    AND profile_id IN (
      SELECT id FROM "public"."profiles" WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own journal entries"
  ON "public"."journal_entries" FOR UPDATE
  USING (user_id = auth.uid());

CREATE POLICY "Users can delete own journal entries"
  ON "public"."journal_entries" FOR DELETE
  USING (user_id = auth.uid());

GRANT ALL ON TABLE "public"."journal_entries" TO "authenticated";
GRANT ALL ON TABLE "public"."journal_entries" TO "service_role";
