-- Huntly World scavenger hunts: consume published huntly_* catalog, World-owned
-- progress/XP/photos. Secrets (lock codes, trivia answers) stay off the client;
-- unlock / validate / end-session go through SECURITY DEFINER RPCs.
--
-- Postgres 15+ (supabase/config.toml). Patterns from Supabase docs:
-- - SET search_path on SECURITY DEFINER functions
-- - auth.uid() ownership checks inside definers
-- - REVOKE EXECUTE FROM PUBLIC/anon; GRANT TO authenticated
-- - Catalog via security_barrier views that omit secrets (base huntly_* stay
--   service-role only for the Huntly Express API)
--
-- Client-facing surface (mobile later):
--   Views:  scavenger_quests_public, scavenger_quest_groups_public,
--           scavenger_quest_items_public, scavenger_quest_locks_public
--   Tables: scavenger_quest_states (SELECT), scavenger_unlocks (SELECT),
--           scavenger_session_photos (SELECT/INSERT/DELETE)
--   Storage bucket: scavenger-photos (path prefix = auth.uid())
--   RPCs:
--     scavenger_is_play_unlocked(type, item_id)
--     scavenger_unlock_with_code(type, item_id, code)
--     scavenger_unlock_with_location(type, item_id, lat, lng)
--     scavenger_ensure_quest_state(profile_id, quest_id)
--     scavenger_mark_item_found(profile_id, item_id)
--     scavenger_validate_item_answer(profile_id, item_id, answer)
--     scavenger_end_session(profile_id, quest_id)  -- XP = unpaid finds × 5
--     scavenger_discard_session_photos(profile_id, quest_id)
--     scavenger_group_completion_status(profile_id, group_id)
--   type = 'quest' | 'questGroup'
--   user_achievements: source='scavenger', source_id=scavenger_quest_states.id,
--     message='Hunt session: found N items.'

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. World progress + unlocks + session photos
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE public.scavenger_quest_states (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id      bigint NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  quest_id        uuid   NOT NULL REFERENCES public.huntly_quests (id) ON DELETE CASCADE,
  found_items     uuid[] NOT NULL DEFAULT '{}',
  items_rewarded  uuid[] NOT NULL DEFAULT '{}',
  complete        boolean NOT NULL DEFAULT false,
  is_current      boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT scavenger_quest_states_profile_quest_unique UNIQUE (profile_id, quest_id)
);

CREATE INDEX scavenger_quest_states_profile_id_idx
  ON public.scavenger_quest_states (profile_id);
CREATE INDEX scavenger_quest_states_quest_id_idx
  ON public.scavenger_quest_states (quest_id);
CREATE INDEX scavenger_quest_states_profile_complete_idx
  ON public.scavenger_quest_states (profile_id, complete);

COMMENT ON COLUMN public.scavenger_quest_states.items_rewarded IS
  'Quest item IDs already awarded XP in a prior session end.';

ALTER TABLE public.scavenger_quest_states ENABLE ROW LEVEL SECURITY;

-- Progress writes go through RPCs only (prevents spoofing found_items / items_rewarded).
CREATE POLICY "Users can view own scavenger quest states"
  ON public.scavenger_quest_states FOR SELECT TO authenticated
  USING (profile_id IN (SELECT id FROM public.profiles WHERE user_id = (SELECT auth.uid())));

GRANT SELECT ON public.scavenger_quest_states TO authenticated;
GRANT ALL ON public.scavenger_quest_states TO service_role;

-- Unlocks are per auth user (same as Huntly firebase_user_id unlock logs), not per profile.
CREATE TABLE public.scavenger_unlocks (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  type           text NOT NULL CHECK (type IN ('quest', 'questGroup')),
  item_id        uuid NOT NULL,
  unlock_source  text CHECK (unlock_source IS NULL OR unlock_source IN ('code', 'location')),
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT scavenger_unlocks_user_type_item_unique UNIQUE (user_id, type, item_id)
);

CREATE INDEX scavenger_unlocks_user_id_idx ON public.scavenger_unlocks (user_id);
CREATE INDEX scavenger_unlocks_item_id_idx ON public.scavenger_unlocks (item_id);

ALTER TABLE public.scavenger_unlocks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own scavenger unlocks"
  ON public.scavenger_unlocks FOR SELECT TO authenticated
  USING (user_id = (SELECT auth.uid()));

-- Inserts/updates go through RPCs only (no direct client write).
GRANT SELECT ON public.scavenger_unlocks TO authenticated;
GRANT ALL ON public.scavenger_unlocks TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.scavenger_unlocks_id_seq TO service_role;

CREATE TABLE public.scavenger_session_photos (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        uuid   NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  profile_id     bigint NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  quest_id       uuid   NOT NULL REFERENCES public.huntly_quests (id) ON DELETE CASCADE,
  quest_item_id  uuid   REFERENCES public.huntly_quest_items (id) ON DELETE SET NULL,
  photo_url      text   NOT NULL,
  item_name      text,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX scavenger_session_photos_profile_quest_idx
  ON public.scavenger_session_photos (profile_id, quest_id);
CREATE INDEX scavenger_session_photos_user_id_idx
  ON public.scavenger_session_photos (user_id);

ALTER TABLE public.scavenger_session_photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own scavenger session photos"
  ON public.scavenger_session_photos FOR SELECT TO authenticated
  USING (user_id = (SELECT auth.uid()));

CREATE POLICY "Users can insert own scavenger session photos"
  ON public.scavenger_session_photos FOR INSERT TO authenticated
  WITH CHECK (
    user_id = (SELECT auth.uid())
    AND profile_id IN (SELECT id FROM public.profiles WHERE user_id = (SELECT auth.uid()))
  );

CREATE POLICY "Users can delete own scavenger session photos"
  ON public.scavenger_session_photos FOR DELETE TO authenticated
  USING (user_id = (SELECT auth.uid()));

GRANT SELECT, INSERT, DELETE ON public.scavenger_session_photos TO authenticated;
GRANT ALL ON public.scavenger_session_photos TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.scavenger_session_photos_id_seq TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. Photo storage (World bucket, journal-photos pattern)
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'scavenger-photos',
  'scavenger-photos',
  true,
  10485760,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic']
)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Users can upload own scavenger photos"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'scavenger-photos'
    AND (storage.foldername(name))[1] = (SELECT auth.uid())::text
  );

CREATE POLICY "Users can view own scavenger photos"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'scavenger-photos'
    AND (storage.foldername(name))[1] = (SELECT auth.uid())::text
  );

CREATE POLICY "Public read scavenger photos"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'scavenger-photos');

CREATE POLICY "Users can delete own scavenger photos"
  ON storage.objects FOR DELETE TO authenticated
  USING (
    bucket_id = 'scavenger-photos'
    AND (storage.foldername(name))[1] = (SELECT auth.uid())::text
  );

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. Catalog views (omit lock codes + trivia answers)
--     Default view security (definer) so authenticated can read published
--     rows without granting base huntly_* tables to clients.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW public.scavenger_quests_public
WITH (security_barrier = true) AS
SELECT
  q.id,
  q.name,
  q.description,
  q.cover_image_url,
  q.tile_image_url,
  q.tags,
  q.published,
  q.is_grouped,
  q.lockable,
  q.group_id,
  q.lock_id,
  q.attraction_logo_url,
  q.attraction_colour_hex,
  q.attraction_name,
  q.attraction_bio,
  q.attraction_image_url,
  q.attraction_fun_facts,
  q.attraction_website,
  q.attraction_address,
  q.attraction_lat,
  q.attraction_lng,
  q.on_completion,
  q.created_at,
  q.updated_at
FROM public.huntly_quests q
WHERE q.published = true;

CREATE OR REPLACE VIEW public.scavenger_quest_groups_public
WITH (security_barrier = true) AS
SELECT
  g.id,
  g.name,
  g.description,
  g.cover_image_url,
  g.display_order,
  g.tags,
  g.published,
  g.lockable,
  g.lock_id,
  g.on_completion,
  g.created_at,
  g.updated_at
FROM public.huntly_quest_groups g
WHERE g.published = true;

CREATE OR REPLACE VIEW public.scavenger_quest_items_public
WITH (security_barrier = true) AS
SELECT
  i.id,
  i.quest_id,
  i.name,
  i.image_url,
  i.branded,
  i.description,
  i.hint,
  i.tags,
  i.warning,
  i.lat,
  i.lng,
  i.question,
  (i.question IS NOT NULL AND btrim(i.question) <> '') AS has_question,
  i."order",
  i.created_at,
  i.updated_at
FROM public.huntly_quest_items i
INNER JOIN public.huntly_quests q ON q.id = i.quest_id
WHERE q.published = true;

-- Lock metadata without passcode (only locks referenced by published content).
CREATE OR REPLACE VIEW public.scavenger_quest_locks_public
WITH (security_barrier = true) AS
SELECT
  l.id,
  l.types,
  l.permanent_unlock,
  l.location_lat,
  l.location_lng,
  l.location_radius,
  ('code' = ANY (l.types)) AS requires_code,
  ('location' = ANY (l.types)) AS requires_location
FROM public.huntly_quest_locks l
WHERE l.id IN (
  SELECT q.lock_id FROM public.huntly_quests q
  WHERE q.published = true AND q.lock_id IS NOT NULL
  UNION
  SELECT g.lock_id FROM public.huntly_quest_groups g
  WHERE g.published = true AND g.lock_id IS NOT NULL
);

GRANT SELECT ON public.scavenger_quests_public TO authenticated;
GRANT SELECT ON public.scavenger_quest_groups_public TO authenticated;
GRANT SELECT ON public.scavenger_quest_items_public TO authenticated;
GRANT SELECT ON public.scavenger_quest_locks_public TO authenticated;
GRANT SELECT ON public.scavenger_quests_public TO service_role;
GRANT SELECT ON public.scavenger_quest_groups_public TO service_role;
GRANT SELECT ON public.scavenger_quest_items_public TO service_role;
GRANT SELECT ON public.scavenger_quest_locks_public TO service_role;

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. Internal helpers
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.scavenger_assert_profile_owner(p_profile_id bigint)
RETURNS uuid
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_owner uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT p.user_id INTO v_owner
  FROM public.profiles p
  WHERE p.id = p_profile_id;

  IF v_owner IS NULL THEN
    RAISE EXCEPTION 'Profile not found';
  END IF;

  IF v_owner <> v_uid THEN
    RAISE EXCEPTION 'Not authorized for this profile';
  END IF;

  RETURN v_uid;
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_assert_profile_owner(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.scavenger_assert_profile_owner(bigint) TO service_role;

CREATE OR REPLACE FUNCTION public.scavenger_distance_meters(
  p_lat1 double precision,
  p_lng1 double precision,
  p_lat2 double precision,
  p_lng2 double precision
)
RETURNS double precision
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  SELECT 6371000.0 * 2.0 * asin(
    sqrt(
      power(sin(radians(p_lat2 - p_lat1) / 2.0), 2) +
      cos(radians(p_lat1)) * cos(radians(p_lat2)) *
      power(sin(radians(p_lng2 - p_lng1) / 2.0), 2)
    )
  );
$$;

REVOKE ALL ON FUNCTION public.scavenger_distance_meters(double precision, double precision, double precision, double precision)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.scavenger_distance_meters(double precision, double precision, double precision, double precision)
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.scavenger_get_lock_for_target(
  p_type text,
  p_item_id uuid
)
RETURNS public.huntly_quest_locks
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_lock_id uuid;
  v_lock public.huntly_quest_locks;
  v_published boolean;
  v_lockable boolean;
BEGIN
  IF p_type = 'quest' THEN
    SELECT q.lock_id, q.published, q.lockable
    INTO v_lock_id, v_published, v_lockable
    FROM public.huntly_quests q
    WHERE q.id = p_item_id;
  ELSIF p_type = 'questGroup' THEN
    SELECT g.lock_id, g.published, g.lockable
    INTO v_lock_id, v_published, v_lockable
    FROM public.huntly_quest_groups g
    WHERE g.id = p_item_id;
  ELSE
    RAISE EXCEPTION 'Invalid type: %', p_type;
  END IF;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Target not found';
  END IF;

  IF NOT coalesce(v_published, false) THEN
    RAISE EXCEPTION 'Target is not published';
  END IF;

  IF NOT coalesce(v_lockable, false) OR v_lock_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT * INTO v_lock
  FROM public.huntly_quest_locks l
  WHERE l.id = v_lock_id;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  RETURN v_lock;
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_get_lock_for_target(text, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.scavenger_get_lock_for_target(text, uuid) TO service_role;

CREATE OR REPLACE FUNCTION public.scavenger_is_play_unlocked(
  p_type text,
  p_item_id uuid
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_lock public.huntly_quest_locks;
  v_row public.scavenger_unlocks;
  v_dual boolean;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  v_lock := public.scavenger_get_lock_for_target(p_type, p_item_id);

  -- No lock / not lockable => playable
  IF v_lock IS NULL THEN
    RETURN true;
  END IF;

  SELECT * INTO v_row
  FROM public.scavenger_unlocks u
  WHERE u.user_id = v_uid
    AND u.type = p_type
    AND u.item_id = p_item_id;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  -- Dual-lock (code + location): only a code unlock grants play access
  -- (matches Huntly unlockLogs.isPlayUnlocked).
  v_dual :=
    ('code' = ANY (v_lock.types))
    AND ('location' = ANY (v_lock.types));

  IF v_dual THEN
    RETURN v_row.unlock_source = 'code';
  END IF;

  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_is_play_unlocked(text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.scavenger_is_play_unlocked(text, uuid) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.scavenger_record_unlock(
  p_type text,
  p_item_id uuid,
  p_source text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_existing public.scavenger_unlocks;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_source IS NOT NULL AND p_source NOT IN ('code', 'location') THEN
    RAISE EXCEPTION 'Invalid unlock_source';
  END IF;

  SELECT * INTO v_existing
  FROM public.scavenger_unlocks u
  WHERE u.user_id = v_uid
    AND u.type = p_type
    AND u.item_id = p_item_id;

  IF FOUND THEN
    IF p_source = 'code' AND v_existing.unlock_source IS DISTINCT FROM 'code' THEN
      UPDATE public.scavenger_unlocks
      SET unlock_source = 'code'
      WHERE id = v_existing.id;
    END IF;
    RETURN;
  END IF;

  INSERT INTO public.scavenger_unlocks (user_id, type, item_id, unlock_source)
  VALUES (v_uid, p_type, p_item_id, p_source);
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_record_unlock(text, uuid, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.scavenger_record_unlock(text, uuid, text) TO service_role;

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. Unlock RPCs (code / location) — Huntly parity
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.scavenger_unlock_with_code(
  p_type text,
  p_item_id uuid,
  p_code text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_lock public.huntly_quest_locks;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_code IS NULL OR btrim(p_code) = '' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'missing_code');
  END IF;

  v_lock := public.scavenger_get_lock_for_target(p_type, p_item_id);

  IF v_lock IS NULL THEN
    RETURN jsonb_build_object('ok', true, 'unlocked', true, 'reason', 'no_lock');
  END IF;

  IF NOT ('code' = ANY (v_lock.types)) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'code_not_required');
  END IF;

  IF v_lock.code IS NULL OR lower(btrim(v_lock.code)) <> lower(btrim(p_code)) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'incorrect_code');
  END IF;

  -- Dual-lock: replace any stale location unlock with a code unlock
  IF ('location' = ANY (v_lock.types)) THEN
    DELETE FROM public.scavenger_unlocks
    WHERE user_id = v_uid
      AND type = p_type
      AND item_id = p_item_id;
  END IF;

  PERFORM public.scavenger_record_unlock(p_type, p_item_id, 'code');

  RETURN jsonb_build_object(
    'ok', true,
    'unlocked', true,
    'play_unlocked', public.scavenger_is_play_unlocked(p_type, p_item_id)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_unlock_with_code(text, uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.scavenger_unlock_with_code(text, uuid, text) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.scavenger_unlock_with_location(
  p_type text,
  p_item_id uuid,
  p_lat double precision,
  p_lng double precision
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_lock public.huntly_quest_locks;
  v_dist double precision;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_lat IS NULL OR p_lng IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'missing_coordinates');
  END IF;

  v_lock := public.scavenger_get_lock_for_target(p_type, p_item_id);

  IF v_lock IS NULL THEN
    RETURN jsonb_build_object('ok', true, 'unlocked', true, 'reason', 'no_lock');
  END IF;

  IF NOT ('location' = ANY (v_lock.types)) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'location_not_required');
  END IF;

  IF v_lock.location_lat IS NULL OR v_lock.location_lng IS NULL OR v_lock.location_radius IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'lock_missing_location');
  END IF;

  v_dist := public.scavenger_distance_meters(
    p_lat, p_lng, v_lock.location_lat, v_lock.location_lng
  );

  IF v_dist > v_lock.location_radius THEN
    RETURN jsonb_build_object(
      'ok', false,
      'reason', 'out_of_range',
      'distance_meters', v_dist,
      'radius_meters', v_lock.location_radius
    );
  END IF;

  PERFORM public.scavenger_record_unlock(p_type, p_item_id, 'location');

  RETURN jsonb_build_object(
    'ok', true,
    'unlocked', true,
    'play_unlocked', public.scavenger_is_play_unlocked(p_type, p_item_id),
    'distance_meters', v_dist
  );
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_unlock_with_location(text, uuid, double precision, double precision)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.scavenger_unlock_with_location(text, uuid, double precision, double precision)
  TO authenticated, service_role;

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. Quest state + mark found + trivia
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.scavenger_ensure_quest_state(
  p_profile_id bigint,
  p_quest_id uuid
)
RETURNS public.scavenger_quest_states
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_state public.scavenger_quest_states;
  v_published boolean;
BEGIN
  PERFORM public.scavenger_assert_profile_owner(p_profile_id);

  SELECT q.published INTO v_published
  FROM public.huntly_quests q
  WHERE q.id = p_quest_id;

  IF NOT FOUND OR NOT coalesce(v_published, false) THEN
    RAISE EXCEPTION 'Quest not found or not published';
  END IF;

  SELECT * INTO v_state
  FROM public.scavenger_quest_states s
  WHERE s.profile_id = p_profile_id
    AND s.quest_id = p_quest_id;

  IF FOUND THEN
    RETURN v_state;
  END IF;

  INSERT INTO public.scavenger_quest_states (profile_id, quest_id)
  VALUES (p_profile_id, p_quest_id)
  RETURNING * INTO v_state;

  RETURN v_state;
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_ensure_quest_state(bigint, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.scavenger_ensure_quest_state(bigint, uuid) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.scavenger_mark_item_found(
  p_profile_id bigint,
  p_item_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_item public.huntly_quest_items;
  v_quest public.huntly_quests;
  v_state public.scavenger_quest_states;
  v_total integer;
  v_found uuid[];
BEGIN
  PERFORM public.scavenger_assert_profile_owner(p_profile_id);

  SELECT * INTO v_item
  FROM public.huntly_quest_items i
  WHERE i.id = p_item_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Quest item not found';
  END IF;

  SELECT * INTO v_quest
  FROM public.huntly_quests q
  WHERE q.id = v_item.quest_id;

  IF NOT FOUND OR NOT coalesce(v_quest.published, false) THEN
    RAISE EXCEPTION 'Quest not found or not published';
  END IF;

  IF NOT public.scavenger_is_play_unlocked('quest', v_quest.id) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_unlocked');
  END IF;

  -- Trivia items must go through scavenger_validate_item_answer
  IF v_item.question IS NOT NULL AND btrim(v_item.question) <> '' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'requires_answer');
  END IF;

  v_state := public.scavenger_ensure_quest_state(p_profile_id, v_quest.id);

  IF p_item_id = ANY (v_state.found_items) THEN
    RETURN jsonb_build_object(
      'ok', true,
      'already_found', true,
      'found_items', to_jsonb(v_state.found_items),
      'complete', v_state.complete
    );
  END IF;

  v_found := array_append(v_state.found_items, p_item_id);

  SELECT count(*)::integer INTO v_total
  FROM public.huntly_quest_items i
  WHERE i.quest_id = v_quest.id;

  UPDATE public.scavenger_quest_states
  SET
    found_items = v_found,
    complete = (cardinality(v_found) >= v_total AND v_total > 0),
    updated_at = now()
  WHERE id = v_state.id
  RETURNING * INTO v_state;

  RETURN jsonb_build_object(
    'ok', true,
    'already_found', false,
    'found_items', to_jsonb(v_state.found_items),
    'complete', v_state.complete
  );
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_mark_item_found(bigint, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.scavenger_mark_item_found(bigint, uuid) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.scavenger_validate_item_answer(
  p_profile_id bigint,
  p_item_id uuid,
  p_answer text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_item public.huntly_quest_items;
  v_quest public.huntly_quests;
  v_state public.scavenger_quest_states;
  v_has_question boolean;
  v_correct boolean;
  v_found uuid[];
  v_total integer;
BEGIN
  PERFORM public.scavenger_assert_profile_owner(p_profile_id);

  IF p_answer IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'missing_answer');
  END IF;

  IF char_length(p_answer) > 1000 THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'answer_too_long');
  END IF;

  SELECT * INTO v_item
  FROM public.huntly_quest_items i
  WHERE i.id = p_item_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Quest item not found';
  END IF;

  SELECT * INTO v_quest
  FROM public.huntly_quests q
  WHERE q.id = v_item.quest_id;

  IF NOT FOUND OR NOT coalesce(v_quest.published, false) THEN
    RAISE EXCEPTION 'Quest not found or not published';
  END IF;

  IF NOT public.scavenger_is_play_unlocked('quest', v_quest.id) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_unlocked');
  END IF;

  v_has_question := v_item.question IS NOT NULL AND btrim(v_item.question) <> '';

  IF NOT v_has_question THEN
    RETURN jsonb_build_object(
      'ok', true,
      'is_correct', false,
      'has_question', false,
      'item_marked_as_found', false
    );
  END IF;

  v_correct :=
    lower(btrim(coalesce(v_item.answer, ''))) = lower(btrim(p_answer));

  IF NOT v_correct THEN
    RETURN jsonb_build_object(
      'ok', true,
      'is_correct', false,
      'has_question', true,
      'item_marked_as_found', false
    );
  END IF;

  v_state := public.scavenger_ensure_quest_state(p_profile_id, v_quest.id);

  IF p_item_id = ANY (v_state.found_items) THEN
    RETURN jsonb_build_object(
      'ok', true,
      'is_correct', true,
      'has_question', true,
      'item_marked_as_found', true,
      'already_found', true,
      'complete', v_state.complete
    );
  END IF;

  v_found := array_append(v_state.found_items, p_item_id);

  SELECT count(*)::integer INTO v_total
  FROM public.huntly_quest_items i
  WHERE i.quest_id = v_quest.id;

  UPDATE public.scavenger_quest_states
  SET
    found_items = v_found,
    complete = (cardinality(v_found) >= v_total AND v_total > 0),
    updated_at = now()
  WHERE id = v_state.id
  RETURNING * INTO v_state;

  RETURN jsonb_build_object(
    'ok', true,
    'is_correct', true,
    'has_question', true,
    'item_marked_as_found', true,
    'already_found', false,
    'found_items', to_jsonb(v_state.found_items),
    'complete', v_state.complete
  );
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_validate_item_answer(bigint, uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.scavenger_validate_item_answer(bigint, uuid, text) TO authenticated, service_role;

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. End session → user_achievements (unpaid finds × 5)
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.scavenger_end_session(
  p_profile_id bigint,
  p_quest_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid;
  v_state public.scavenger_quest_states;
  v_team_id bigint;
  v_unpaid uuid[];
  v_n integer;
  v_xp integer;
  v_message text;
  v_achievement_id bigint;
BEGIN
  v_uid := public.scavenger_assert_profile_owner(p_profile_id);

  SELECT * INTO v_state
  FROM public.scavenger_quest_states s
  WHERE s.profile_id = p_profile_id
    AND s.quest_id = p_quest_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'ok', true,
      'awarded', false,
      'items_found_this_session', 0,
      'xp', 0
    );
  END IF;

  SELECT ARRAY(
    SELECT x
    FROM unnest(v_state.found_items) AS x
    WHERE NOT (x = ANY (v_state.items_rewarded))
  ) INTO v_unpaid;

  v_n := coalesce(cardinality(v_unpaid), 0);

  IF v_n = 0 THEN
    RETURN jsonb_build_object(
      'ok', true,
      'awarded', false,
      'items_found_this_session', 0,
      'xp', 0,
      'quest_state_id', v_state.id,
      'complete', v_state.complete
    );
  END IF;

  SELECT ud.team INTO v_team_id
  FROM public.user_data ud
  WHERE ud.user_id = v_uid;

  IF v_team_id IS NULL THEN
    RAISE EXCEPTION 'User has no team; cannot award scavenger XP';
  END IF;

  v_xp := v_n * 5;
  v_message := format('Hunt session: found %s items.', v_n);

  INSERT INTO public.user_achievements (
    profile_id,
    team_id,
    source,
    source_id,
    message,
    xp
  ) VALUES (
    p_profile_id,
    v_team_id,
    'scavenger',
    v_state.id,
    v_message,
    v_xp
  )
  RETURNING id INTO v_achievement_id;

  UPDATE public.scavenger_quest_states
  SET
    items_rewarded = (
      SELECT ARRAY(
        SELECT DISTINCT x
        FROM unnest(v_state.items_rewarded || v_unpaid) AS x
      )
    ),
    updated_at = now()
  WHERE id = v_state.id
  RETURNING * INTO v_state;

  RETURN jsonb_build_object(
    'ok', true,
    'awarded', true,
    'items_found_this_session', v_n,
    'item_ids', to_jsonb(v_unpaid),
    'xp', v_xp,
    'achievement_id', v_achievement_id,
    'quest_state_id', v_state.id,
    'complete', v_state.complete,
    'message', v_message
  );
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_end_session(bigint, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.scavenger_end_session(bigint, uuid) TO authenticated, service_role;

-- Discard in-progress session photos for a profile/quest (Huntly end-session discard).
CREATE OR REPLACE FUNCTION public.scavenger_discard_session_photos(
  p_profile_id bigint,
  p_quest_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_deleted integer;
BEGIN
  PERFORM public.scavenger_assert_profile_owner(p_profile_id);

  DELETE FROM public.scavenger_session_photos
  WHERE profile_id = p_profile_id
    AND quest_id = p_quest_id
    AND user_id = auth.uid();

  GET DIAGNOSTICS v_deleted = ROW_COUNT;

  RETURN jsonb_build_object('ok', true, 'deleted', v_deleted);
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_discard_session_photos(bigint, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.scavenger_discard_session_photos(bigint, uuid) TO authenticated, service_role;

-- Group completion status (Huntly: all member quests fully found + optional CTA).
CREATE OR REPLACE FUNCTION public.scavenger_group_completion_status(
  p_profile_id bigint,
  p_group_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_published boolean;
  v_on_completion jsonb;
  v_all_completed boolean;
  v_quest_count integer;
BEGIN
  PERFORM public.scavenger_assert_profile_owner(p_profile_id);

  SELECT g.published, g.on_completion
  INTO v_published, v_on_completion
  FROM public.huntly_quest_groups g
  WHERE g.id = p_group_id;

  IF NOT FOUND OR NOT coalesce(v_published, false) THEN
    RAISE EXCEPTION 'Quest group not found or not published';
  END IF;

  SELECT count(*)::integer INTO v_quest_count
  FROM public.huntly_quests q
  WHERE q.group_id = p_group_id
    AND q.published = true;

  IF v_quest_count = 0 THEN
    v_all_completed := false;
  ELSE
    SELECT bool_and(completed) INTO v_all_completed
    FROM (
      SELECT
        (
          SELECT count(*) FROM public.huntly_quest_items i WHERE i.quest_id = q.id
        ) > 0
        AND (
          SELECT count(*) FROM public.huntly_quest_items i WHERE i.quest_id = q.id
        ) = coalesce(
          (
            SELECT cardinality(s.found_items)
            FROM public.scavenger_quest_states s
            WHERE s.profile_id = p_profile_id
              AND s.quest_id = q.id
          ),
          0
        ) AS completed
      FROM public.huntly_quests q
      WHERE q.group_id = p_group_id
        AND q.published = true
    ) t;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'all_completed', coalesce(v_all_completed, false),
    'has_cta', (v_on_completion IS NOT NULL AND v_on_completion ? 'cta'),
    'on_completion', v_on_completion,
    'quest_count', v_quest_count
  );
END;
$$;

REVOKE ALL ON FUNCTION public.scavenger_group_completion_status(bigint, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.scavenger_group_completion_status(bigint, uuid) TO authenticated, service_role;
