-- Expand Explore catalogue with animals, flora, habitats (images added later).
-- image_path left empty until artwork is uploaded.

INSERT INTO public.explore_cards (
  slug, name, description, category, rarity, image_path, base_weight, habitat_weights, sort_order
) VALUES
  -- Animals
  ('grey-squirrel', 'Grey Squirrel', 'A bushy-tailed climber that dashes up trees and parks. Watch for twitching whiskers and a nut held tight in tiny paws!', 'animal', 'common', '', 10,
    '{"woodland":5,"park_garden":4,"urban":1.5,"general":0.3}'::jsonb, 210),
  ('robin', 'Robin', 'A friendly little bird with a bright red breast. Robins often hop close by on paths, watching for worms in the soil.', 'animal', 'common', '', 10,
    '{"park_garden":5,"woodland":3,"urban":2,"general":0.3}'::jsonb, 220),
  ('magpie', 'Magpie', 'A bold black-and-white bird with a long tail. Magpies chatter loudly from rooftops and hedges, always keeping a sharp eye out.', 'animal', 'common', '', 10,
    '{"urban":4,"park_garden":4,"farmland":2,"general":0.3}'::jsonb, 230),
  ('ladybird', 'Ladybird', 'A tiny round beetle with red wing cases and black spots. Ladybirds help gardens by munching on aphids.', 'animal', 'common', '', 10,
    '{"park_garden":5,"grassland":3,"farmland":2,"general":0.3}'::jsonb, 240),
  ('peacock-butterfly', 'Peacock Butterfly', 'A butterfly with eye-spots like a peacock’s feathers. It opens its wings wide to startle hungry birds.', 'animal', 'common', '', 10,
    '{"grassland":4,"park_garden":4,"woodland":2,"general":0.25}'::jsonb, 250),
  ('grey-heron', 'Grey Heron', 'A tall, patient fisher that stands still by the water’s edge. When a fish swims near — spear! — dinner is caught.', 'animal', 'uncommon', '', 5,
    '{"freshwater":5,"wetland":4,"general":0.2}'::jsonb, 260),
  ('hedgehog', 'Hedgehog', 'A snuffling night explorer covered in spines. Hedgehogs roll into a prickly ball when scared, then uncurl to hunt beetles.', 'animal', 'uncommon', '', 5,
    '{"park_garden":5,"woodland":3,"urban":1.5,"general":0.25}'::jsonb, 270),
  ('swallow', 'Swallow', 'A sleek summer flyer with a forked tail. Swallows swoop low over fields, catching insects on the wing.', 'animal', 'uncommon', '', 5,
    '{"farmland":5,"grassland":4,"freshwater":1,"general":0.25}'::jsonb, 280),
  ('smooth-newt', 'Smooth Newt', 'A little amphibian with a long tail and soft skin. Newts hide under stones by day and swim in ponds in spring.', 'animal', 'uncommon', '', 5,
    '{"freshwater":5,"wetland":4,"park_garden":1,"general":0.2}'::jsonb, 290),
  ('slow-worm', 'Slow Worm', 'Not a worm and not a snake — a legless lizard with shiny skin! It loves warm banks and compost heaps.', 'animal', 'uncommon', '', 5,
    '{"grassland":4,"park_garden":3,"farmland":2,"general":0.2}'::jsonb, 300),
  ('badger', 'Badger', 'A strong digger with a striped face and short legs. Badgers live in underground setts and come out at dusk.', 'animal', 'rare', '', 6,
    '{"woodland":5,"farmland":2,"general":0.2}'::jsonb, 310),
  ('barn-owl', 'Barn Owl', 'A pale, silent hunter that glides over fields at night. Its heart-shaped face helps it hear the tiniest rustle.', 'animal', 'rare', '', 6,
    '{"farmland":5,"grassland":3,"general":0.2}'::jsonb, 320),
  ('stoat', 'Stoat', 'A slim, speedy hunter with a black-tipped tail. Stoats zip through hedges looking for mice and rabbits.', 'animal', 'rare', '', 6,
    '{"farmland":4,"grassland":4,"woodland":2,"general":0.2}'::jsonb, 330),
  ('red-squirrel', 'Red Squirrel', 'A rare, tufty-eared climber with a rusty-red coat. Spotting one in the trees is a special woodland treat!', 'animal', 'very_rare', '', 3,
    '{"woodland":5,"general":0.15}'::jsonb, 340),
  ('pine-marten', 'Pine Marten', 'A shy tree acrobat with chocolate-brown fur and a creamy throat patch. Pine martens are hard to find — keep your eyes peeled!', 'animal', 'very_rare', '', 3,
    '{"woodland":5,"general":0.15}'::jsonb, 350),
  ('peregrine-falcon', 'Peregrine Falcon', 'The world’s fastest bird when it dives. Peregrines nest on cliffs and tall city buildings, hunting other birds mid-air.', 'animal', 'very_rare', '', 3,
    '{"urban":4,"farmland":2,"general":0.2}'::jsonb, 360),

  -- Flora & wildlife
  ('dandelion', 'Dandelion', 'A sunny yellow flower that turns into a fluffy seed clock. Blow the seeds and watch them float away on the breeze!', 'flora_wildlife', 'common', '', 10,
    '{"grassland":5,"park_garden":4,"urban":1,"general":0.3}'::jsonb, 370),
  ('bramble', 'Bramble', 'A tangle of thorny stems that grows juicy blackberries. Birds and bugs love the flowers, and explorers love the fruit!', 'flora_wildlife', 'common', '', 10,
    '{"woodland":4,"park_garden":3,"farmland":3,"general":0.25}'::jsonb, 380),
  ('birch-tree', 'Birch Tree', 'A graceful tree with papery white bark. Birch leaves flutter in the wind and feed many little insects.', 'flora_wildlife', 'common', '', 10,
    '{"woodland":5,"park_garden":2,"general":0.25}'::jsonb, 390),
  ('holly', 'Holly', 'An evergreen with shiny spiked leaves and bright red berries. Holly stays green all winter when other trees look bare.', 'flora_wildlife', 'common', '', 10,
    '{"woodland":4,"park_garden":4,"general":0.25}'::jsonb, 400),
  ('bluebell', 'Bluebell', 'A carpet of nodding blue flowers in spring woods. Whole paths can turn violet-blue when bluebells bloom together.', 'flora_wildlife', 'uncommon', '', 5,
    '{"woodland":5,"general":0.2}'::jsonb, 410),
  ('primrose', 'Primrose', 'A pale yellow spring flower that peeps out early. Primroses like banks, woods, and sunny grassy edges.', 'flora_wildlife', 'uncommon', '', 5,
    '{"woodland":4,"grassland":3,"park_garden":2,"general":0.25}'::jsonb, 420),
  ('wild-garlic', 'Wild Garlic', 'A woodland plant with white starry flowers and a garlicky smell. Crush a leaf gently — you’ll know it at once!', 'flora_wildlife', 'uncommon', '', 5,
    '{"woodland":5,"freshwater":1,"general":0.2}'::jsonb, 430),
  ('rowan-tree', 'Rowan Tree', 'Also called the mountain ash. In autumn it hangs with bright orange-red berries that birds adore.', 'flora_wildlife', 'uncommon', '', 5,
    '{"woodland":4,"park_garden":2,"farmland":1,"general":0.25}'::jsonb, 440),
  ('ancient-yew', 'Ancient Yew', 'An evergreen that can live for thousands of years. Its dark needles and red berry-cups make churchyards feel timeless.', 'flora_wildlife', 'rare', '', 6,
    '{"woodland":3,"park_garden":4,"general":0.2}'::jsonb, 450),
  ('bee-orchid', 'Bee Orchid', 'A wild orchid whose flower looks like a resting bee! Finding one in a sunny meadow is a true explorer’s prize.', 'flora_wildlife', 'very_rare', '', 3,
    '{"grassland":5,"farmland":2,"general":0.15}'::jsonb, 460),

  -- Habitats
  ('river-habitat', 'River Habitat', 'Moving fresh water with banks, stones, and riffles. Fish, birds, and otters all use rivers as highways through the land.', 'habitat', 'common', '', 10,
    '{"freshwater":5,"wetland":2,"general":0.2}'::jsonb, 470),
  ('farmland-habitat', 'Farmland Habitat', 'Fields, crops, and quiet lanes. Hedgerows and field edges give birds and bugs places to hide and feed.', 'habitat', 'common', '', 10,
    '{"farmland":5,"grassland":2,"general":0.25}'::jsonb, 480),
  ('hedgerow-habitat', 'Hedgerow Habitat', 'A living fence of shrubs and trees. Hedgerows are busy corridors where mice, birds, and insects travel safely.', 'habitat', 'uncommon', '', 5,
    '{"farmland":5,"grassland":3,"park_garden":1,"general":0.2}'::jsonb, 490),
  ('wetland-habitat', 'Wetland Habitat', 'Marshy ground where water and land meet. Reeds, wading birds, and dragonflies thrive in these soggy spots.', 'habitat', 'uncommon', '', 5,
    '{"wetland":5,"freshwater":3,"general":0.2}'::jsonb, 500),
  ('forest-floor-habitat', 'Forest Floor Habitat', 'The shady carpet under the trees — moss, fungi, fallen leaves, and tiny creatures. Lift a log (gently!) and you may find secrets.', 'habitat', 'rare', '', 6,
    '{"woodland":5,"general":0.2}'::jsonb, 510),
  ('orchard-habitat', 'Orchard Habitat', 'Rows of fruit trees with blossom in spring and apples in autumn. Bees buzz between flowers while birds nest in the branches.', 'habitat', 'rare', '', 6,
    '{"farmland":4,"park_garden":3,"grassland":1,"general":0.2}'::jsonb, 520)
ON CONFLICT (slug) DO NOTHING;
