CREATE TABLE "public"."seasons" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "name" text,
  "hero_image" text,
  "story" text
);

ALTER TABLE "public"."seasons" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for seasons"
  ON "public"."seasons" FOR SELECT TO public USING (true);

CREATE POLICY "Allow service_role full access to seasons"
  ON "public"."seasons" FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE "public"."chapters" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "season_id" bigint NOT NULL REFERENCES "public"."seasons"(id) ON DELETE CASCADE,
  "week_number" integer NOT NULL CHECK (week_number >= 1 AND week_number <= 12),
  "title" text NOT NULL,
  "image" text,
  "body" text,
  "unlock_date" date NOT NULL
);

CREATE UNIQUE INDEX chapters_season_week_key ON "public"."chapters"(season_id, week_number);

ALTER TABLE "public"."chapters" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for chapters"
  ON "public"."chapters" FOR SELECT TO public USING (true);

CREATE POLICY "Allow service_role full access to chapters"
  ON "public"."chapters" FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE "public"."chapter_activities" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "chapter_id" bigint NOT NULL REFERENCES "public"."chapters"(id) ON DELETE CASCADE,
  "activity_id" bigint NOT NULL REFERENCES "public"."activities"(id) ON DELETE CASCADE,
  "order" integer NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX chapter_activities_chapter_activity_key ON "public"."chapter_activities"(chapter_id, activity_id);

ALTER TABLE "public"."chapter_activities" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for chapter_activities"
  ON "public"."chapter_activities" FOR SELECT TO public USING (true);

CREATE POLICY "Allow service_role full access to chapter_activities"
  ON "public"."chapter_activities" FOR ALL TO service_role USING (true) WITH CHECK (true);

GRANT ALL ON "public"."seasons" TO anon, authenticated, service_role;
GRANT ALL ON "public"."chapters" TO anon, authenticated, service_role;
GRANT ALL ON "public"."chapter_activities" TO anon, authenticated, service_role;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'season-images',
  'season-images',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public read for season-images"
  ON storage.objects FOR SELECT USING (bucket_id = 'season-images');

CREATE POLICY "Service role can manage season-images"
  ON storage.objects FOR ALL TO service_role USING (bucket_id = 'season-images') WITH CHECK (bucket_id = 'season-images');

CREATE POLICY "Authenticated upload for season-images"
  ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'season-images' AND auth.role() = 'authenticated');
