-- Public waitlist signups (website form). May already exist on prod from dashboard work.
CREATE TABLE IF NOT EXISTS "public"."waitlist_signups" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "name" text,
  "email" text NOT NULL,
  "notes" text,
  "source" text
);

ALTER TABLE "public"."waitlist_signups" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous waitlist signup" ON "public"."waitlist_signups";
CREATE POLICY "Allow anonymous waitlist signup"
  ON "public"."waitlist_signups" FOR INSERT TO anon
  WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated waitlist signup" ON "public"."waitlist_signups";
CREATE POLICY "Allow authenticated waitlist signup"
  ON "public"."waitlist_signups" FOR INSERT TO authenticated
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON "public"."waitlist_signups" TO service_role;

COMMENT ON TABLE "public"."waitlist_signups" IS 'Marketing waitlist from the public site; reads via admin (service_role).';
