-- Account removal requests: users submit a reason; admins approve before removal.
CREATE TABLE "public"."account_removal_requests" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  "reason" text,
  "status" text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
  "created_at" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "public"."account_removal_requests" ENABLE ROW LEVEL SECURITY;

-- Users can create their own request and read their own requests (e.g. to cancel within 24h).
CREATE POLICY "Users can insert own account_removal_request"
  ON "public"."account_removal_requests" FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can select own account_removal_requests"
  ON "public"."account_removal_requests" FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

-- Users can update their own request only to cancel (status = 'cancelled') while pending.
CREATE POLICY "Users can update own pending request to cancelled"
  ON "public"."account_removal_requests" FOR UPDATE TO authenticated
  USING (auth.uid() = user_id AND status = 'pending')
  WITH CHECK (auth.uid() = user_id AND status = 'cancelled');

-- Admins need to read/update for approval (admin app uses service_role or add admin policy).
GRANT SELECT, UPDATE ON "public"."account_removal_requests" TO service_role;

COMMENT ON TABLE "public"."account_removal_requests" IS 'User requests for account removal; admin approves before deletion.';
