-- Create user_activity_photos table
CREATE TABLE "public"."user_activity_photos" (
    "photo_id" bigint generated by default as identity not null,
    "profile_id" bigint not null,
    "photo_url" text not null
);

-- Add primary key
ALTER TABLE "public"."user_activity_photos" ADD CONSTRAINT "user_activity_photos_pkey" PRIMARY KEY ("photo_id");

-- Add foreign key to profiles
ALTER TABLE "public"."user_activity_photos" ADD CONSTRAINT "user_activity_photos_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles" ("id") ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE "public"."user_activity_photos" ENABLE ROW LEVEL SECURITY;

-- Policies: users can manage photos for their own profiles
CREATE POLICY "Users can view their own activity photos" ON "public"."user_activity_photos"
    FOR SELECT USING (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can insert their own activity photos" ON "public"."user_activity_photos"
    FOR INSERT WITH CHECK (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can update their own activity photos" ON "public"."user_activity_photos"
    FOR UPDATE USING (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can delete their own activity photos" ON "public"."user_activity_photos"
    FOR DELETE USING (profile_id IN (SELECT id FROM profiles WHERE user_id = auth.uid()));

-- Grant permissions
GRANT ALL ON TABLE "public"."user_activity_photos" TO "authenticated";
GRANT ALL ON TABLE "public"."user_activity_photos" TO "service_role";

-- Index for lookups by profile
CREATE INDEX "user_activity_photos_profile_id_idx" ON "public"."user_activity_photos" ("profile_id");
