-- Temporary submissions: admin-seeded photos so missions / club feed / team Social
-- do not look empty before real explorers submit.

CREATE TABLE IF NOT EXISTS public.temporary_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id bigint NOT NULL REFERENCES public.activities (id) ON DELETE CASCADE,
  display_name text NOT NULL,
  team_id bigint NOT NULL REFERENCES public.teams (id) ON DELETE RESTRICT,
  submitted_at timestamptz NOT NULL DEFAULT now(),
  xp integer NOT NULL DEFAULT 0,
  team_xp_awarded integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS temporary_submissions_activity_id_idx
  ON public.temporary_submissions (activity_id);

CREATE INDEX IF NOT EXISTS temporary_submissions_team_id_idx
  ON public.temporary_submissions (team_id);

CREATE INDEX IF NOT EXISTS temporary_submissions_submitted_at_idx
  ON public.temporary_submissions (submitted_at DESC);

CREATE TABLE IF NOT EXISTS public.temporary_submission_photos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  temporary_submission_id bigint NOT NULL
    REFERENCES public.temporary_submissions (id) ON DELETE CASCADE,
  photo_url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS temporary_submission_photos_submission_id_idx
  ON public.temporary_submission_photos (temporary_submission_id);

ALTER TABLE public.temporary_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.temporary_submission_photos ENABLE ROW LEVEL SECURITY;

-- Authenticated clients can read seed content (mirrors approved club photos).
CREATE POLICY "Authenticated can read temporary submissions"
  ON public.temporary_submissions
  FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Authenticated can read temporary submission photos"
  ON public.temporary_submission_photos
  FOR SELECT TO authenticated
  USING (true);

GRANT SELECT ON TABLE public.temporary_submissions TO authenticated;
GRANT SELECT ON TABLE public.temporary_submission_photos TO authenticated;
GRANT ALL ON TABLE public.temporary_submissions TO service_role;
GRANT ALL ON TABLE public.temporary_submission_photos TO service_role;

-- Storage: public read; uploads go through admin service role (bypasses RLS).
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'temporary-submission-photos',
  'temporary-submission-photos',
  true,
  15728640,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public read temporary-submission-photos"
  ON storage.objects
  FOR SELECT
  USING (bucket_id = 'temporary-submission-photos');

CREATE POLICY "Authenticated insert temporary-submission-photos"
  ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'temporary-submission-photos');

CREATE POLICY "Authenticated update temporary-submission-photos"
  ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'temporary-submission-photos');

CREATE POLICY "Authenticated delete temporary-submission-photos"
  ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'temporary-submission-photos');

-- Club feed: mix approved real photos with temporary submission photos.
-- Temporary photo_ids are negative (-temporary_submission_photos.id) to avoid collisions.
CREATE OR REPLACE FUNCTION public.get_random_club_photos(
  p_count integer DEFAULT 6,
  p_exclude_ids bigint[] DEFAULT '{}'
)
RETURNS TABLE (
  photo_id bigint,
  photo_url text,
  profile_id bigint,
  activity_title text,
  nickname text,
  team_name text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH real_pool AS (
    SELECT
      p.photo_id,
      p.photo_url,
      p.profile_id,
      p.activity_id,
      NULL::text AS nickname,
      NULL::text AS team_name,
      false AS is_temp
    FROM public.user_activity_photos p
    WHERE p.status = 1
      AND p.activity_id IS NOT NULL
      AND (
        cardinality(p_exclude_ids) = 0
        OR NOT (p.photo_id = ANY (p_exclude_ids))
      )
    ORDER BY p.photo_id DESC
    LIMIT GREATEST(p_count * 12, 72)
  ),
  temp_pool AS (
    SELECT
      (-tp.id)::bigint AS photo_id,
      tp.photo_url,
      NULL::bigint AS profile_id,
      ts.activity_id,
      ts.display_name AS nickname,
      lower(t.name::text) AS team_name,
      true AS is_temp
    FROM public.temporary_submission_photos tp
    INNER JOIN public.temporary_submissions ts ON ts.id = tp.temporary_submission_id
    INNER JOIN public.teams t ON t.id = ts.team_id
    WHERE (
      cardinality(p_exclude_ids) = 0
      OR NOT ((-tp.id)::bigint = ANY (p_exclude_ids))
    )
    ORDER BY tp.id DESC
    LIMIT GREATEST(p_count * 12, 72)
  ),
  pool AS (
    SELECT * FROM real_pool
    UNION ALL
    SELECT * FROM temp_pool
  ),
  picked AS (
    SELECT *
    FROM pool
    ORDER BY random()
    LIMIT GREATEST(p_count, 0)
  )
  SELECT
    pk.photo_id,
    pk.photo_url,
    pk.profile_id,
    COALESCE(a.title, '')::text AS activity_title,
    CASE
      WHEN pk.is_temp THEN COALESCE(pk.nickname, '')::text
      ELSE COALESCE(pp.nickname, '')::text
    END AS nickname,
    CASE
      WHEN pk.is_temp THEN COALESCE(pk.team_name, '')::text
      ELSE COALESCE(lower(pp.team_name::text), '')::text
    END AS team_name
  FROM picked pk
  LEFT JOIN public.activities a ON a.id = pk.activity_id
  LEFT JOIN public.profile_public pp ON pp.id = pk.profile_id;
$$;

GRANT EXECUTE ON FUNCTION public.get_random_club_photos(integer, bigint[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_random_club_photos(integer, bigint[]) TO service_role;
