-- Persisted monthly team winners (survives user_achievements cleanup; seeded via SQL editor or cron)
CREATE TABLE "public"."team_monthly_winners" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "year" integer NOT NULL,
    "month" integer NOT NULL CHECK ("month" >= 1 AND "month" <= 12),
    "team_id" bigint NOT NULL REFERENCES "public"."teams" ("id") ON DELETE CASCADE,
    "total_xp" integer NOT NULL DEFAULT 0,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "team_monthly_winners_year_month_key" UNIQUE ("year", "month")
);

CREATE INDEX "team_monthly_winners_team_id_idx" ON "public"."team_monthly_winners" ("team_id");

ALTER TABLE "public"."team_monthly_winners" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can view monthly winners" ON "public"."team_monthly_winners"
    FOR SELECT
    TO authenticated
    USING (true);

GRANT SELECT ON TABLE "public"."team_monthly_winners" TO "authenticated";
GRANT ALL ON TABLE "public"."team_monthly_winners" TO "service_role";
