-- Types/table/policies below may already exist here — see
-- 20260505000000_backfill_campfire_sessions_for_rebuild_order.sql, which
-- creates them earlier so a from-scratch rebuild doesn't break on
-- 20260529120000_campfire_realtime_scheduled_wait.sql. Guarded to no-op in
-- that case; unaffected on environments where this migration ran first.

DO $$ BEGIN
  CREATE TYPE campfire_session_status AS ENUM (
    'draft',
    'scheduled',
    'live',
    'replay',
    'archived'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE campfire_component_type AS ENUM (
    'audio',
    'subtitle',
    'mission_card',
    'submission'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Main campfire sessions table
CREATE TABLE IF NOT EXISTS "public"."campfire_sessions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "title" text NOT NULL,
  "status" campfire_session_status NOT NULL DEFAULT 'draft',
  "scheduled_at" timestamptz,
  "duration" integer,
  "description" text,
  "thumbnail_url" text,
  "missions" bigint[] NOT NULL DEFAULT '{}'
);

ALTER TABLE "public"."campfire_sessions" ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read sessions that are not drafts (scheduled/live/replay)
DO $$ BEGIN
  CREATE POLICY "Authenticated read non-draft campfire_sessions"
    ON "public"."campfire_sessions" FOR SELECT TO authenticated
    USING (status IN ('scheduled', 'live', 'replay'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "Service role full access to campfire_sessions"
    ON "public"."campfire_sessions" FOR ALL TO service_role
    USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

GRANT ALL ON "public"."campfire_sessions" TO anon, authenticated, service_role;

-- Timeline tracks (named layers within a session)
CREATE TABLE "public"."campfire_session_tracks" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "session_id" bigint NOT NULL REFERENCES "public"."campfire_sessions"(id) ON DELETE CASCADE,
  "name" text NOT NULL,
  "type" campfire_component_type NOT NULL,
  "position" integer NOT NULL DEFAULT 0
);

CREATE INDEX campfire_session_tracks_session_id_idx ON "public"."campfire_session_tracks"(session_id);

ALTER TABLE "public"."campfire_session_tracks" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated read campfire_session_tracks"
  ON "public"."campfire_session_tracks" FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM campfire_sessions s
      WHERE s.id = session_id
        AND s.status IN ('scheduled', 'live', 'replay')
    )
  );

CREATE POLICY "Service role full access to campfire_session_tracks"
  ON "public"."campfire_session_tracks" FOR ALL TO service_role
  USING (true) WITH CHECK (true);

GRANT ALL ON "public"."campfire_session_tracks" TO anon, authenticated, service_role;

-- Individual timed components placed on tracks
CREATE TABLE "public"."campfire_session_components" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "session_id" bigint NOT NULL REFERENCES "public"."campfire_sessions"(id) ON DELETE CASCADE,
  "track_id" bigint NOT NULL REFERENCES "public"."campfire_session_tracks"(id) ON DELETE CASCADE,
  "type" campfire_component_type NOT NULL,
  "start_time" integer NOT NULL DEFAULT 0,
  "duration" integer NOT NULL DEFAULT 5000,
  "data" jsonb NOT NULL DEFAULT '{}'
);

CREATE INDEX campfire_session_components_session_id_idx ON "public"."campfire_session_components"(session_id);
CREATE INDEX campfire_session_components_track_id_idx ON "public"."campfire_session_components"(track_id);

ALTER TABLE "public"."campfire_session_components" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated read campfire_session_components"
  ON "public"."campfire_session_components" FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM campfire_sessions s
      WHERE s.id = session_id
        AND s.status IN ('scheduled', 'live', 'replay')
    )
  );

CREATE POLICY "Service role full access to campfire_session_components"
  ON "public"."campfire_session_components" FOR ALL TO service_role
  USING (true) WITH CHECK (true);

GRANT ALL ON "public"."campfire_session_components" TO anon, authenticated, service_role;

-- Storage bucket for campfire audio files
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'campfire-audio',
  'campfire-audio',
  true,
  52428800,
  ARRAY['audio/mpeg', 'audio/mp3', 'audio/wav', 'audio/ogg', 'audio/aac', 'audio/m4a']
)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public read for campfire-audio"
  ON storage.objects FOR SELECT USING (bucket_id = 'campfire-audio');

CREATE POLICY "Service role can manage campfire-audio"
  ON storage.objects FOR ALL TO service_role
  USING (bucket_id = 'campfire-audio') WITH CHECK (bucket_id = 'campfire-audio');

CREATE POLICY "Authenticated upload for campfire-audio"
  ON storage.objects FOR INSERT WITH CHECK (
    bucket_id = 'campfire-audio' AND auth.role() = 'authenticated'
  );
