-- Parent resources table: downloadable/printable resources for the Parent Zone in the app
CREATE TABLE "public"."parent_resources" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "title" text NOT NULL,
  "description" text,
  "file_url" text NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "category" text
);

ALTER TABLE "public"."parent_resources" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for parent_resources"
  ON "public"."parent_resources" FOR SELECT TO public USING (true);

CREATE POLICY "Allow service_role full access for parent_resources"
  ON "public"."parent_resources" FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Storage bucket for resource files (PDF + images)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'parent-resources',
  'parent-resources',
  true,
  15728640,
  ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public read for parent-resources"
  ON storage.objects FOR SELECT USING (bucket_id = 'parent-resources');

CREATE POLICY "Service role can manage parent-resources"
  ON storage.objects FOR ALL TO service_role USING (bucket_id = 'parent-resources') WITH CHECK (bucket_id = 'parent-resources');

CREATE POLICY "Authenticated upload for parent-resources"
  ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'parent-resources' AND auth.role() = 'authenticated');
